### ISSUE TITLE
Crash on IBGNetworkLog

### ISSUE THREAD

**Issue by GlisboaDev** [Instabug/Instabug-React-Native#316]
We're having crashes from `IBGNetworkLog+CoreDataClass.m:126` with a message `-[__NSCFConstantString allKeys]: unrecognized selector sent to instance`.

We don't use any extra feature for the network logging, so all the settings are the default.

### Steps to Reproduce the Problem
Unknown, happens randomly to our users.

### Expected Behavior
Not crash the app.

### Integration code
```
import Instabug, { BugReporting } from 'instabug-reactnative';

    Instabug.startWithToken('',
      [Instabug.invocationEvent.shake]
    );
    Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);
    Instabug.setCrashReportingEnabled(false);

    BugReporting.setPromptOptionsEnabled(false, true, true);
    BugReporting.onInvokeHandler(() => {
      logInfo();
    });
    Instabug.setEnabledAttachmentTypes(true, false, false, false);
```

### SDK Version
`8.4.2`

### Logs
```
Frameworks/CoreFoundation.framework/CoreFoundation___exceptionPreprocess	
/usr/lib/libobjc.A.dylib_objc_exception_throw	
Frameworks/CoreFoundation.framework/CoreFoundation-[NSObject(NSObject) doesNotRecognizeSelector:]	
Frameworks/CoreFoundation.framework/CoreFoundation____forwarding___	
Frameworks/CoreFoundation.framework/CoreFoundation___forwarding_prep_0___	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Persistence/Core Data/Models/IBGNetworkLog+CoreDataClass.m:126:25-[IBGNetworkLog toDictionary]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:195:29__82-[IBGNetworkLoggerPersistenceManager loadLogsAsynchronouslyWithCompletionHandler:]_block_invoke	
/Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:9__43-[IBGDALService readASync:completionBlock:]_block_invoke	
Frameworks/CoreData.framework/CoreData_developerSubmittedBlockToNSManagedObjectContextPerform	
/usr/lib/system/libdispatch.dylib__dispatch_client_callout	
/usr/lib/system/libdispatch.dylib__dispatch_lane_serial_drain$VARIANT$mp	
/usr/lib/system/libdispatch.dylib__dispatch_lane_invoke$VARIANT$mp	
/usr/lib/system/libdispatch.dylib__dispatch_workloop_worker_thread	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
/usr/lib/system/libsystem_pthread.dylib_start_wqthread
```

**Comment by HeshamMegid** [comment]
@GlisboaDev we're looking into this issue. In the meantime, do you have a full stack trace including all threads?

**Comment by alyezz** [comment]
@GlisboaDev We just Release 8.4.4. Update and let us know if you have any issues

**Comment by GlisboaDev** [comment]
@HeshamMegid That's all the log I had.
@alyezz will update it and reopen the ticket if I see the issue again, thanks

**Comment by GlisboaDev** [comment]
Still happening on `8.4.4`

got the following logs:
```
NSInvalidArgumentException -[__NSCFConstantString allKeys]: unrecognized selector sent to instance 0x1ffdefbc8 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation -[NSObject(NSObject) doesNotRecognizeSelector:]
    Frameworks/CoreFoundation.framework/CoreFoundation ____forwarding___
    Frameworks/CoreFoundation.framework/CoreFoundation ___forwarding_prep_0___
    /Users/distiller/project/Instabug/InstabugNetworkLogger/Persistence/Core Data/Models/IBGNetworkLog+CoreDataClass.m:126:25 -[IBGNetworkLog toDictionary]
    /Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:168:33 __59-[IBGNetworkLoggerPersistenceManager loadLogsSynchronously]_block_invoke
    /Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:147:9 __26-[IBGDALService readSync:]_block_invoke
    Frameworks/CoreData.framework/CoreData _developerSubmittedBlockToNSManagedObjectContextPerform
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_lane_barrier_sync_invoke_and_complete
    Frameworks/CoreData.framework/CoreData -[NSManagedObjectContext performBlockAndWait:]
    /Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:137:5 -[IBGDALService readSync:]
    /Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:155:5 -[IBGNetworkLoggerPersistenceManager loadLogsSynchronously]
    /Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:247:31 -[IBGNetworkLoggerPersistenceManager loadSnapshotSynchronously:withCompletionHandler:]
    /Users/distiller/project/Instabug/InstabugNetworkLogger/InstabugNetworkLogger.m:62:5 -[InstabugNetworkLogger loadSnapshotSynchronously:withCompletionHandler:]
    /Users/distiller/project/Instabug/InstabugCore/Logging/IBGSnapshotManager.m:207:9 -[IBGSnapshotManager takePostSendingSnapshotWithSnapshot:Synchronously:]
    /Users/distiller/project/Instabug/InstabugCore/Models/IBGLogLocalAttachment.m:51:38 -[IBGLogLocalAttachment initWithDelegate:logType:snapShot:isSynchronouslyFetch:]
    /Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:138:26 +[IBGCrashCreator attachLogsToCrash:snapshot:isHandled:]
    /Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:101:5 +[IBGCrashCreator crashModelInstanceWithSnapshot:Handled:]
    /Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:36:51 __53+[IBGCrashCreator creatCrashAndSaveItWithStackTrace:]_block_invoke
    /Users/distiller/project/Instabug/InstabugCore/Logging/IBGDataStore.m:13 -[IBGDataStore excutePreSendingBlockSynchronized:completionHandler:]
    /Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:35:5 +[IBGCrashCreator creatCrashAndSaveItWithStackTrace:]
    /Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashManager.m:267:5 +[IBGCrashManager postCrashHandler]
    Frameworks/Instabug.framework/Instabug signal_handler_callback
    Frameworks/Instabug.framework/Instabug internal_callback_iterator(int, __siginfo*, __darwin_ucontext*, void*)
    Frameworks/Instabug.framework/Instabug IBGplcrash_signal_handler
    /usr/lib/system/libsystem_platform.dylib __sigtramp
    /usr/lib/system/libsystem_pthread.dylib _pthread_kill$VARIANT$armv81
    /usr/lib/system/libsystem_c.dylib _abort
    /usr/lib/system/libsystem_c.dylib ___assert_rtn
    /Users/vagrant/git/packages/mobile/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1349:3 -[RCTSRWebSocket stream:handleEvent:]
    Frameworks/CoreFoundation.framework/CoreFoundation __signalEventSync
    Frameworks/CoreFoundation.framework/CoreFoundation __cfstream_shared_signalEventSync
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopDoSource0
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopDoSources0
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    Frameworks/Foundation.framework/Foundation -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
    /Users/vagrant/git/packages/mobile/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1592:12 -[_RCTSRRunLoopThread main]
    Frameworks/Foundation.framework/Foundation ___NSThread__start__
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start
    /usr/lib/system/libsystem_pthread.dylib _thread_start
```


```
Frameworks/CoreFoundation.framework/CoreFoundation___exceptionPreprocess	
/usr/lib/libobjc.A.dylib_objc_exception_throw	
Frameworks/CoreFoundation.framework/CoreFoundation-[NSObject(NSObject) doesNotRecognizeSelector:]	
Frameworks/CoreFoundation.framework/CoreFoundation____forwarding___	
Frameworks/CoreFoundation.framework/CoreFoundation___forwarding_prep_0___	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Persistence/Core Data/Models/IBGNetworkLog+CoreDataClass.m:126:25-[IBGNetworkLog toDictionary]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:168:33__59-[IBGNetworkLoggerPersistenceManager loadLogsSynchronously]_block_invoke	
/Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:147:9__26-[IBGDALService readSync:]_block_invoke	
Frameworks/CoreData.framework/CoreData_developerSubmittedBlockToNSManagedObjectContextPerform	
/usr/lib/system/libdispatch.dylib__dispatch_client_callout	
/usr/lib/system/libdispatch.dylib__dispatch_lane_barrier_sync_invoke_and_complete	
Frameworks/CoreData.framework/CoreData-[NSManagedObjectContext performBlockAndWait:]	
/Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:137:5-[IBGDALService readSync:]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:155:5-[IBGNetworkLoggerPersistenceManager loadLogsSynchronously]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:247:31-[IBGNetworkLoggerPersistenceManager loadSnapshotSynchronously:withCompletionHandler:]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/InstabugNetworkLogger.m:62:5-[InstabugNetworkLogger loadSnapshotSynchronously:withCompletionHandler:]	
/Users/distiller/project/Instabug/InstabugCore/Logging/IBGSnapshotManager.m:207:9-[IBGSnapshotManager takePostSendingSnapshotWithSnapshot:Synchronously:]	
/Users/distiller/project/Instabug/InstabugCore/Models/IBGLogLocalAttachment.m:51:38-[IBGLogLocalAttachment initWithDelegate:logType:snapShot:isSynchronouslyFetch:]	
/Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:138:26+[IBGCrashCreator attachLogsToCrash:snapshot:isHandled:]	
/Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:101:5+[IBGCrashCreator crashModelInstanceWithSnapshot:Handled:]	
/Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:36:51__53+[IBGCrashCreator creatCrashAndSaveItWithStackTrace:]_block_invoke	
/Users/distiller/project/Instabug/InstabugCore/Logging/IBGDataStore.m:13-[IBGDataStore excutePreSendingBlockSynchronized:completionHandler:]	
/Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashCreator.m:35:5+[IBGCrashCreator creatCrashAndSaveItWithStackTrace:]	
/Users/distiller/project/Instabug/InstabugCrashReporting/Managers/IBGCrashManager.m:267:5+[IBGCrashManager postCrashHandler]	
Frameworks/Instabug.framework/Instabugsignal_handler_callback	
Frameworks/Instabug.framework/Instabuginternal_callback_iterator(int, __siginfo*, __darwin_ucontext*, void*)	
Frameworks/Instabug.framework/InstabugIBGplcrash_signal_handler	
/usr/lib/system/libsystem_platform.dylib__sigtramp	
/usr/lib/system/libsystem_pthread.dylib_pthread_kill$VARIANT$armv81	
/usr/lib/system/libsystem_c.dylib_abort	
/usr/lib/system/libsystem_c.dylib___assert_rtn	
/Users/vagrant/git/packages/mobile/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1349:3-[RCTSRWebSocket stream:handleEvent:]	
Frameworks/CoreFoundation.framework/CoreFoundation__signalEventSync	
Frameworks/CoreFoundation.framework/CoreFoundation__cfstream_shared_signalEventSync	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopDoSource0	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopDoSources0	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/Foundation.framework/Foundation-[NSRunLoop(NSRunLoop) runMode:beforeDate:]	
/Users/vagrant/git/packages/mobile/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1592:12-[_RCTSRRunLoopThread main]	
Frameworks/Foundation.framework/Foundation___NSThread__start__	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
/usr/lib/system/libsystem_pthread.dylib_thread_start	
Thread 0·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
PrivateFrameworks/GraphicsServices.framework/GraphicsServices_GSEventRunModal	
PrivateFrameworks/UIKitCore.framework/UIKitCore_UIApplicationMain	
Loadboard/main.m:12:12main	
/usr/lib/system/libdyld.dylib_start	
Thread 1·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/Foundation.framework/Foundation-[NSRunLoop(NSRunLoop) runMode:beforeDate:]	
Frameworks/Foundation.framework/Foundation-[NSRunLoop(NSRunLoop) runUntilDate:]	
PrivateFrameworks/UIKitCore.framework/UIKitCore-[UIEventFetcher threadMain]	
Frameworks/Foundation.framework/Foundation___NSThread__start__	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 2·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
/usr/lib/system/libsystem_kernel.dylib_thread_suspend	
/Users/vagrant/git/packages/mobile/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/KSCrash/Source/KSCrash/Recording/Sentry/BSG_KSCrashSentry_MachException.c:210:9ksmachexc_i_handleExceptions	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 3·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
/Users/vagrant/git/packages/mobile/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/KSCrash/Source/KSCrash/Recording/Sentry/BSG_KSCrashSentry_MachException.c:217:28ksmachexc_i_handleExceptions	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 4·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
/Users/vagrant/git/packages/mobile/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:243:36+[RCTCxxBridge runRunLoop]	
Frameworks/Foundation.framework/Foundation___NSThread__start__	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 5·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
/usr/lib/libc++.1.dylibstd::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorevoid std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebmalloc::Scavenger::threadRunLoop()	
Frameworks/JavaScriptCore.framework/JavaScriptCorebmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*)	
Frameworks/JavaScriptCore.framework/JavaScriptCorevoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 6·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
PrivateFrameworks/WebCore.framework/WebCoreRunWebThread(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 7·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/CFNetwork.framework/CFNetwork-[__CoreSchedulingSetRunnable runForever]	
Frameworks/Foundation.framework/Foundation___NSThread__start__	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 9·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRun	
Frameworks/CoreMotion.framework/CoreMotion0x18677423c (-0x4ef30000 + 7875478076)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 10·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 11·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/Instabug.framework/Instabugexception_server_thread	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 12·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 13·
/usr/lib/system/libsystem_kernel.dylib_select$DARWIN_EXTSN	
Frameworks/CoreFoundation.framework/CoreFoundation___CFSocketManager	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 14·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 15·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 16·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 17·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/AVFoundation.framework/Frameworks/AVFAudio.framework/AVFAudioGenericRunLoopThread::Entry(void*)	
Frameworks/AVFoundation.framework/Frameworks/AVFAudio.framework/AVFAudioCAPThread::Entry(CAPThread*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 18·
/usr/lib/system/libsystem_kernel.dylib___workq_kernreturn	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
Thread 19·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 20·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 21·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 22·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 23·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
Thread 24·
/usr/lib/system/libsystem_kernel.dylib___psynch_cvwait	
/usr/lib/system/libsystem_pthread.dylib__pthread_cond_wait$VARIANT$armv81	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCorebool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)	
Frameworks/JavaScriptCore.framework/JavaScriptCoreWTF::wtfThreadEntryPoint(void*)	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start
```

**Comment by HeshamMegid** [comment]
@GlisboaDev thanks for the stack trace. We're looking into it.

**Comment by alyezz** [comment]
@GlisboaDev we just release 8.5.0 the issue is fixed there.

The problem was that in some cases, `xhrNetworkInterceptor` library we use returned empty headers when trying to get the response's headers. We added some defensive coding to prevent this issue from happening again.

**Comment by HeshamMegid** [comment]
Closing this for now. Please reopen this issue if you're still seeing the crash on v8.5.

**Comment by GlisboaDev** [comment]
Issue still not fixed.
Just happened again with a different stack. This time it happened with me when shaking to report a bug, then it shows success popup and freezes, then crash
```
nsexception
{
  "name": "NSInvalidArgumentException",
  "referenced_object": {
    "address": 8072414568,
    "type": "objc_object",
    "class": "__NSCFConstantString"
  }
}
reason
-[__NSCFConstantString allKeys]: unrecognized selector sent to instance 0x1e1274568
type
nsexception


Frameworks/CoreFoundation.framework/CoreFoundation___exceptionPreprocess	
/usr/lib/libobjc.A.dylib_objc_exception_throw	
Frameworks/CoreFoundation.framework/CoreFoundation-[NSObject(NSObject) doesNotRecognizeSelector:]	
Frameworks/CoreFoundation.framework/CoreFoundation____forwarding___	
Frameworks/CoreFoundation.framework/CoreFoundation___forwarding_prep_0___	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Persistence/Core Data/Models/IBGNetworkLog+CoreDataClass.m:126:25-[IBGNetworkLog toDictionary]	
/Users/distiller/project/Instabug/InstabugNetworkLogger/Modules/IBGNetworkLoggerPersistenceManager.m:195:29__82-[IBGNetworkLoggerPersistenceManager loadLogsAsynchronouslyWithCompletionHandler:]_block_invoke	
/Users/distiller/project/Instabug/InstabugCoreDataLayer/IBGDALService.m:9__43-[IBGDALService readASync:completionBlock:]_block_invoke	
Frameworks/CoreData.framework/CoreData_developerSubmittedBlockToNSManagedObjectContextPerform	
/usr/lib/system/libdispatch.dylib__dispatch_client_callout	
/usr/lib/system/libdispatch.dylib__dispatch_lane_serial_drain	
/usr/lib/system/libdispatch.dylib__dispatch_lane_invoke	
/usr/lib/system/libdispatch.dylib__dispatch_workloop_worker_thread	
/usr/lib/system/libsystem_pthread.dylib__pthread_wqthread	
/usr/lib/system/libsystem_pthread.dylib_start_wqthread	
Thread 0·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
PrivateFrameworks/GraphicsServices.framework/GraphicsServices_GSEventRunModal	
PrivateFrameworks/UIKitCore.framework/UIKitCore_UIApplicationMain	
Loadboard/main.m:12:12main	
/usr/lib/system/libdyld.dylib_start	
Thread 1·
/usr/lib/system/libsystem_kernel.dylib_mach_msg_trap	
/usr/lib/system/libsystem_kernel.dylib_mach_msg	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopServiceMachPort	
Frameworks/CoreFoundation.framework/CoreFoundation___CFRunLoopRun	
Frameworks/CoreFoundation.framework/CoreFoundation_CFRunLoopRunSpecific	
Frameworks/Foundation.framework/Foundation-[NSRunLoop(NSRunLoop) runMode:beforeDate:]	
Frameworks/Foundation.framework/Foundation-[NSRunLoop(NSRunLoop) runUntilDate:]	
PrivateFrameworks/UIKitCore.framework/UIKitCore-[UIEventFetcher threadMain]	
Frameworks/Foundation.framework/Foundation-[NSThread main]	
Frameworks/Foundation.framework/Foundation___NSThread__start__	
/usr/lib/system/libsystem_pthread.dylib__pthread_body	
/usr/lib/system/libsystem_pthread.dylib__pthread_start	
```

**Comment by HeshamMegid** [comment]
@GlisboaDev sorry, we missed your reply on the closed issue. 

Since the top part of the stack trace is identical to the crashes coming from earlier versions, can you please confirm that this stack trace is indeed from version 8.4.4 or above?

In the meantime, we're adding more defensive code from the native side to make sure that when XHR return invalid data to us, this doesn't happen.

**Comment by GlisboaDev** [comment]
Yes I checked the version and it's exactly 8.4.4

**Comment by HeshamMegid** [comment]
Sorry for the confusion here. As @alyezz mentioned, the issue was fixed in 8.5, not 8.4.4 

> @GlisboaDev we just release 8.5.0 the issue is fixed there.

I've referenced the wrong version above. Please update to the latest version which includes this fix.

**Comment by GlisboaDev** [comment]
Are you sure of this @HeshamMegid ? According to your changelog it's on `8.4.4`

```
Release v8.5.0
@InstabugCI InstabugCI released this 26 days ago · 34 commits to master since this release

⚠️ If you are using React Native 0.60, please follow our migration guide here

Support for React Native 0.60
Updates native iOS and Android SDKs to version 8.5
Assets
2
 v8.4.4
 b226de0
Release v8.4.4
@InstabugCI InstabugCI released this 29 days ago · 36 commits to master since this release

Fixes an issue that causes the sdk to crash when a network request has no headers.
```
