### ISSUE TITLE
Crash occurs every time when launching the app on iOS

### ISSUE THREAD

**Issue by mrarronz** [Instabug/Instabug-React-Native#490]
One of our customers has reported that every time he uses the app, the app crashes during launching process. This makes the customer frustrated. From the crash log we can see this is probably caused by Instabug library.

### Steps to Reproduce the Problem
Just launching the app

### Expected Behavior
No crash

### Actual Behavior
App crashes in every launching process.

### Instabug integration code
```
Instabug.startWithToken(TOKEN, [Instabug.invocationEvent.shake]);
    Instabug.setViewHierarchyEnabled(true);
    Instabug.setTrackUserSteps(true);
    Instabug.setReproStepsMode(Instabug.reproStepsMode.enabledWithNoScreenshots);
    BugReporting.setShakingThresholdForAndroid(shakeThresholdForAndroid);
    BugReporting.setInvocationOptions([
      BugReporting.invocationOptions.emailFieldOptional,
      BugReporting.invocationOptions.commentFieldRequired,
    ]);
    BugReporting.setEnabled(true);
    Chats.setEnabled(true);
    Replies.setEnabled(true);
    BugReporting.setReportTypes([
      BugReporting.reportType.bug,
      BugReporting.reportType.feedback,
      BugReporting.reportType.question,
    ]);
    Surveys.setShouldShowWelcomeScreen(true);
```

### SDK Version
```
https://github.com/Instabug/Instabug-React-Native.git#customBuild/8.7.3.1
```

### React Native, iOS and Android Versions
React Native: 0.61.2
iOS: 11.0+
Android: 5.0+

### Device Model
iPhone7, iPad 5th generation

### Crash log
```
data:text/text;charset=utf-8,
# Cause: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
# Reported at: 2020-04-24 05:36:19 UTC

Thread 0 [Crashed]:

0    CoreFoundation                           0x1843f5d04     _exceptionPreprocess + 124
1    libobjc.A.dylib                          0x183644528     objc_exception_throw + 55
2    CoreFoundation                           0x18438ebd4     _CFThrowFormattedException + 111
3    CoreFoundation                           0x1842c224c     -[__NSArrayM insertObject:atIndex:] + 1419
4    UIKit                                    0x18d8c202c     -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:] + 527
5    UIKit                                    0x18d8c4a08     -[UIViewController(UIContainerViewControllerProtectedMethods) addChildViewController:] + 99
6    Instabug                                 0x101757bc0     -[IBGSurveyMasterNavigationViewController showViewController:animated:completionHandler:] (IBGSurveyMasterNavigationViewController.m:182)
7    Instabug                                 0x1017577ac     -[IBGSurveyMasterNavigationViewController showIndependentViewController:] (IBGSurveyMasterNavigationViewController.m:142)
8    Instabug                                 0x101757700     -[IBGSurveyMasterNavigationViewController goNext:] (IBGSurveyMasterNavigationViewController.m:134)
9    Instabug                                 0x101757040     -[IBGSurveyMasterNavigationViewController setFirstQuestion:] (IBGSurveyMasterNavigationViewController.m:71)
10   Instabug                                 0x101788464     -[IBGSurveyWelcomeViewController startSurvey] (IBGSurveyWelcomeViewController.m:60)
11   UIKit                                    0x18d861614     -[UIApplication sendAction:to:from:forEvent:] + 95
12   UIKit                                    0x18d861594     -[UIControl sendAction:to:forEvent:] + 79
13   UIKit                                    0x18d84c2fc     -[UIControl _sendActionsForEvents:withEvent:] + 439
14   UIKit                                    0x18d860e88     -[UIControl touchesEnded:withEvent:] + 575
15   UIKit                                    0x18d8609a8     -[UIWindow _sendTouchesForEvent:] + 2543
16   UIKit                                    0x18d85be78     -[UIWindow sendEvent:] + 3207
17   UIKit                                    0x18d82d384     -[UIApplication sendEvent:] + 339
18   Instabug                                 0x101934330     _IBGSwizzle_sendEvent (IBGMethodSwizzler.m:165)
19   UIKit                                    0x18e17a85c     _dispatchPreprocessedEventFromEventQueue + 2363
20   UIKit                                    0x18e17cde8     _handleEventQueueInternal + 4759
21   UIKit                                    0x18e175d04     _handleHIDEventFetcherDrain + 151
22   CoreFoundation                           0x18439e2e8     _CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 23
23   CoreFoundation                           0x18439e268     _CFRunLoopDoSource0 + 87
24   CoreFoundation                           0x18439daf0     _CFRunLoopDoSources0 + 203
25   CoreFoundation                           0x18439b6c8     _CFRunLoopRun + 1047
26   CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
27   GraphicsServices                         0x186153f84     GSEventRunModal + 99
28   UIKit                                    0x18d8902f4     UIApplicationMain + 207
29   MyAppName                                 0x100895fdc     0x100890000
30   libdyld.dylib                            0x183dde56c     $start + 3

Thread 1 [Crashed]:

0    libsystem_kernel.dylib                   0x183f0d348     _pthread_kill + 8
1    libsystem_c.dylib                        0x183e7cfb8     abort + 139
2    Instabug                                 0x10197fc18     uncaught_exception_handler + 27
3    CoreFoundation                           0x1843f6078     _handleUncaughtException + 627
4    libobjc.A.dylib                          0x183644804     _objc_terminate() + 111
5    MyAppName                                 0x100b48de8     0x100890000
6    libc++abi.dylib                          0x18363454c     $std::__terminate(void (*)()) + 15
7    libc++abi.dylib                          0x183634158     _cxa_rethrow + 143
8    libobjc.A.dylib                          0x1836446e8     objc_exception_rethrow + 43
9    CoreFoundation                           0x1842bc024     CFRunLoopRunSpecific + 543
10   GraphicsServices                         0x186153f84     GSEventRunModal + 99
11   UIKit                                    0x18d8902f4     UIApplicationMain + 207
12   MyAppName                                 0x100895fdc     0x100890000
13   libdyld.dylib                            0x183dde56c     $start + 3

Thread 2:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    Foundation                               0x184ce56e4     -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 303
5    Foundation                               0x184d04afc     -[NSRunLoop(NSRunLoop) runUntilDate:] + 95
6    UIKit                                    0x18e3ef2f4     -[UIEventFetcher threadMain] + 135
7    Foundation                               0x184de6860     _NSThread__start__ + 995
8    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
9    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
10   libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 3:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    MyAppName                                 0x100b3642c     0x100890000
2    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
3    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
4    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 4:

0    libsystem_kernel.dylib                   0x183f0d150     _psynch_cvwait + 8
1    libc++.1.dylib                           0x1835c7f34     $std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 95
2    JavaScriptCore                           0x18b669dd0     $std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 123
3    JavaScriptCore                           0x18b669ca4     $std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 107
4    JavaScriptCore                           0x18b669b28     bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 279
5    JavaScriptCore                           0x18b669e20     void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 43
6    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
7    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
8    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 5:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    CFNetwork                                0x184a26264     +[NSURLConnection(Loader) _resourceLoadLoop:] + 403
5    Foundation                               0x184de6860     _NSThread__start__ + 995
6    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
7    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
8    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 6:

0    JavaScriptCore                           0x18b36f4bc     JSC::JSArray::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) + 92
1    JavaScriptCore                           0x18ad5a7cc     llint_slow_path_get_by_val + 4047
2    JavaScriptCore                           0x18b45c27c     llint_entry + 12907
3    JavaScriptCore                           0x18b45f920     llint_entry + 26895
4    JavaScriptCore                           0x18b45f920     llint_entry + 26895
5    JavaScriptCore                           0x18b45f920     llint_entry + 26895
6    JavaScriptCore                           0x18b45f920     llint_entry + 26895
7    JavaScriptCore                           0x18b45f920     llint_entry + 26895
8    JavaScriptCore                           0x18b45f920     llint_entry + 26895
9    JavaScriptCore                           0x18b45f920     llint_entry + 26895
10   JavaScriptCore                           0x18b45f920     llint_entry + 26895
11   JavaScriptCore                           0x18b45f920     llint_entry + 26895
12   JavaScriptCore                           0x18b45f984     llint_entry + 26995
13   JavaScriptCore                           0x18b45f920     llint_entry + 26895
14   JavaScriptCore                           0x18b45f920     llint_entry + 26895
15   JavaScriptCore                           0x18b45f920     llint_entry + 26895
16   JavaScriptCore                           0x18b45f984     llint_entry + 26995
17   JavaScriptCore                           0x18b45f920     llint_entry + 26895
18   JavaScriptCore                           0x18b45f920     llint_entry + 26895
19   JavaScriptCore                           0x18b45f920     llint_entry + 26895
20   JavaScriptCore                           0x18b45f984     llint_entry + 26995
21   JavaScriptCore                           0x18b45f984     llint_entry + 26995
22   JavaScriptCore                           0x18b45f984     llint_entry + 26995
23   JavaScriptCore                           0x18b45f984     llint_entry + 26995
24   JavaScriptCore                           0x18b45f920     llint_entry + 26895
25   JavaScriptCore                           0x18b45f920     llint_entry + 26895
26   JavaScriptCore                           0x18b45f920     llint_entry + 26895
27   JavaScriptCore                           0x18b458e40     vmEntryToJavaScript + 271
28   JavaScriptCore                           0x18b33e948     JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 135
29   JavaScriptCore                           0x18ad63948     JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 399
30   JavaScriptCore                           0x18ae119e4     JSC::boundFunctionCall(JSC::ExecState*) + 527
31   JavaScriptCore                           0x18b4603b8     llint_entry + 29607
32   JavaScriptCore                           0x18b45f984     llint_entry + 26995
33   JavaScriptCore                           0x18b458e40     vmEntryToJavaScript + 271
34   JavaScriptCore                           0x18b33e948     JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 135
35   JavaScriptCore                           0x18ad63948     JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 399
36   JavaScriptCore                           0x18ae119e4     JSC::boundFunctionCall(JSC::ExecState*) + 527
37   JavaScriptCore                           0x18b4603b8     llint_entry + 29607
38   JavaScriptCore                           0x18b45f984     llint_entry + 26995
39   JavaScriptCore                           0x18b45f984     llint_entry + 26995
40   JavaScriptCore                           0x18b45f920     llint_entry + 26895
41   JavaScriptCore                           0x18b45f920     llint_entry + 26895
42   JavaScriptCore                           0x18b45f920     llint_entry + 26895
43   JavaScriptCore                           0x18b45f920     llint_entry + 26895
44   JavaScriptCore                           0x18b45f920     llint_entry + 26895
45   JavaScriptCore                           0x18b45f920     llint_entry + 26895
46   JavaScriptCore                           0x18b458e40     vmEntryToJavaScript + 271
47   JavaScriptCore                           0x18b33e948     JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 135
48   JavaScriptCore                           0x18ad63948     JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 399
49   JavaScriptCore                           0x18b3739f0     JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 451

Thread 7:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    WebCore                                  0x18c12fe04     RunWebThread(void*) + 455
5    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
6    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
7    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 8:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    CoreFoundation                           0x18430b098     CFRunLoopRun + 115
5    CoreMotion                               0x1896b6298     0x0000000186122297 + 951
6    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
7    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
8    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 9:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    Instabug                                 0x10198b3e4     exception_server_thread + 187
2    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
3    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
4    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 10:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    AVFAudio                                 0x189ba4774     GenericRunLoopThread::Entry(void*) + 163
5    AVFAudio                                 0x189bcf018     CAPThread::Entry(CAPThread*) + 83
6    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
7    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
8    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 11:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    CFNetwork                                0x184ba53b8     _privateRunloopEmulationSet(void*) + 263
5    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
6    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
7    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 12:

0    libsystem_kernel.dylib                   0x183eecbc4     mach_msg_trap + 8
1    CoreFoundation                           0x18439dc74     _CFRunLoopServiceMachPort + 195
2    CoreFoundation                           0x18439b840     _CFRunLoopRun + 1423
3    CoreFoundation                           0x1842bbfb8     CFRunLoopRunSpecific + 435
4    CoreFoundation                           0x1843aceb8     _legacyStreamRunLoop_workThread + 271
5    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
6    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
7    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 13:

0    libsystem_kernel.dylib                   0x183eecc18     $semaphore_timedwait_trap + 8
1    libdispatch.dylib                        0x183d7bd40     _dispatch_semaphore_wait_slow + 71
2    libdispatch.dylib                        0x183d876ac     _dispatch_worker_thread + 255
3    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
4    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
5    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 14:

0    libsystem_kernel.dylib                   0x183eecc18     $semaphore_timedwait_trap + 8
1    libdispatch.dylib                        0x183d7bd40     _dispatch_semaphore_wait_slow + 71
2    libdispatch.dylib                        0x183d876ac     _dispatch_worker_thread + 255
3    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
4    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
5    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 15:

0    libsystem_kernel.dylib                   0x183f0d150     _psynch_cvwait + 8
1    JavaScriptCore                           0x18ad310ac     WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 147
2    JavaScriptCore                           0x18b64f898     WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2207
3    JavaScriptCore                           0x18b1ec37c     bool WTF::ConditionBase::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 171
4    JavaScriptCore                           0x18b63cb9c     WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call() + 203
5    JavaScriptCore                           0x18ad2d660     WTF::threadEntryPoint(void*) + 119
6    JavaScriptCore                           0x18ad2d5a0     WTF::wtfThreadEntryPoint(void*) + 83
7    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
8    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
9    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 16:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Thread 17:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Thread 18:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Thread 19:

0    libsystem_kernel.dylib                   0x183f0d570     _select + 8
1    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
2    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
3    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 20:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Thread 21:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Thread 22:

0    libsystem_kernel.dylib                   0x183f0d150     _psynch_cvwait + 8
1    JavaScriptCore                           0x18ad310ac     WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 147
2    JavaScriptCore                           0x18b64f898     WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2207
3    JavaScriptCore                           0x18b1ec37c     bool WTF::ConditionBase::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 171
4    JavaScriptCore                           0x18b63cb9c     WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call() + 203
5    JavaScriptCore                           0x18ad2d660     WTF::threadEntryPoint(void*) + 119
6    JavaScriptCore                           0x18ad2d5a0     WTF::wtfThreadEntryPoint(void*) + 83
7    libsystem_pthread.dylib                  0x18402031c     _pthread_body + 307
8    libsystem_pthread.dylib                  0x1840201e8     _pthread_start + 311
9    libsystem_pthread.dylib                  0x18401ec28     thread_start + 3

Thread 23:

0    libsystem_kernel.dylib                   0x183f0ddbc     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x18401ec20     $start_wqthread + 3

Binary Images:

0x1842b4000     CoreFoundation                               arm64      A595C2EE-553E-3A1F-A695-9947247B034E 
0x18363c000     libobjc.A.dylib                              arm64      5F420CDC-6F59-3721-A9CF-0464BD87E1A2 
0x18d81d000     UIKit                                        arm64      4708CF24-F7C7-3421-9574-CDEB8E3A0763 
0x10174c000     Instabug                                     arm64      0B31ABC0-7D11-3560-B205-9F3FB0C780DA 
0x186149000     GraphicsServices                             arm64      58A9A51F-40F4-39E8-A33B-BFBFAAB3F679 
0x100890000     MyAppName                                     arm64      B3683770-CFCB-32E5-B452-43FF1F97A92E 
0x183ddd000     libdyld.dylib                                arm64      30EEA71A-4F5B-39EE-8C6B-426835348E81 
0x183eec000     libsystem_kernel.dylib                       arm64      2D85F169-EEE7-36C4-8145-938BDEF80A7E 
0x183e1a000     libsystem_c.dylib                            arm64      7FB972B4-47D5-3C13-A4DB-D0627694986E 
0x18361a000     libc++abi.dylib                              arm64      4E4A4BCB-0B63-363D-B460-A93569A74FD6 
0x184cd9000     Foundation                                   arm64      531F6C32-18E6-3E6E-8C67-2E6975DF5429 
0x18401e000     libsystem_pthread.dylib                      arm64      80157CB2-8287-3E53-AFB0-00D8FC29211C 
0x1835c0000     libc++.1.dylib                               arm64      2C929C02-9BAF-3D0F-84A2-E636550AF33C 
0x18ad24000     JavaScriptCore                               arm64      D70C33A4-CB98-3017-B6E3-F873A9CC526F 
0x184977000     CFNetwork                                    arm64      8D01FC28-DB47-3E1C-A098-245BB236B220 
0x18c0ee000     WebCore                                      arm64      64CB5E60-AD39-394A-9488-D7EC006B2A74 
0x189637000     CoreMotion                                   arm64      28EEEEAC-0B4F-3BEB-8B95-9CCFE71A7575 
0x189b20000     AVFAudio                                     arm64      7583A123-2E4D-363F-BFB3-FAD21D33622D 
0x183d78000     libdispatch.dylib                            arm64      A879DAD0-ED5C-3E0B-BFD5-A8C14045BFB3 


```

**Comment by mrarronz** [comment]
This crash already happened many times for multiple users, we have tried to upgrade the Instabug library to the latest version v9.1.1, but there is a strange bug on Android (please see the screenshot on #467 ), so we give up the upgrading and keep version at `#customBuild/8.7.3.1`. Please help, thank you in advance.

**Comment by alyezz** [comment]
@mrarronz i was not able to reproduce the issue above however it is most likely fixed in the newer versions of our iOS SDK, we are planning to release early next week. Will update you on this thread once it's released

**Comment by alyezz** [comment]
@mrarronz we just released 9.1.6, please upgrade and let us know if you have any issues

**Comment by mrarronz** [comment]
Thanks @alyezz , after we tried the latest v9.1.6, we still found the button issue on Android, capture button stay on the screen. This bug does not happen on iOS, so I guess this is a bug inside Android SDK. This bug exists since this library upgraded to v9.0 and later versions. We have decided to upgrade this library to latest version v9.1.6 to resolve iOS crash, but for Android we will still keep it on v8.7.3. Hope you can troubleshoot this button issue on Android and get that fixed asap, thank you very much!

**Comment by mrarronz** [comment]
Upgrade instabug-reactnative to v9.1.6 for iOS, still see crash reports on latest build according to Firebase console. This crash has become a main problem that ruin our user experience.
```
Fatal Exception: NSInvalidArgumentException
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil                 _hidden#243_
```

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18f3f5344 __exceptionPreprocess
1  libobjc.A.dylib                0x18f10acc0 objc_exception_throw
2  CoreFoundation                 0x18f44e550 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x18f44daec -[__NSArrayM insertObject:atIndex:].cold.2
4  CoreFoundation                 0x18f2c6b7c -[__NSArrayM insertObject:atIndex:]
5  UIKitCore                      0x192eb46c0 -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:]
6  Instabug                       0x1058cab1c _hidden#243_ + 184 (__hidden#269_:184)
7  Instabug                       0x1058ca74c _hidden#235_ + 143 (__hidden#269_:143)
8  Instabug                       0x1058ca6a0 _hidden#234_ + 136 (__hidden#269_:136)
9  Instabug                       0x1058ca000 _hidden#226_ + 72 (__hidden#269_:72)
10 Instabug                       0x1058fd440 _hidden#2441_ + 60 (__hidden#2468_:60)
11 UIKitCore                      0x19351eaac -[UIApplication sendAction:to:from:forEvent:]
12 UIKitCore                      0x192f07794 -[UIControl sendAction:to:forEvent:]
13 UIKitCore                      0x192f07afc -[UIControl _sendActionsForEvents:withEvent:]
14 UIKitCore                      0x192f06b14 -[UIControl touchesEnded:withEvent:]
15 UIKitCore                      0x193559e90 -[UIWindow _sendTouchesForEvent:]
16 UIKitCore                      0x19355b670 -[UIWindow sendEvent:]
17 UIKitCore                      0x193536840 -[UIApplication sendEvent:]
18 Instabug                       0x105ab797c __IBGSwizzle_sendEvent + 173 (__hidden#18590_:173)
19 UIKitCore                      0x1935b9da4 __dispatchPreprocessedEventFromEventQueue
20 UIKitCore                      0x1935bc988 __handleEventQueueInternal
21 UIKitCore                      0x1935b48c8 __handleHIDEventFetcherDrain
22 CoreFoundation                 0x18f370d14 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
23 CoreFoundation                 0x18f370c68 __CFRunLoopDoSource0
24 CoreFoundation                 0x18f3703c4 __CFRunLoopDoSources0
25 CoreFoundation                 0x18f36b1fc __CFRunLoopRun
26 CoreFoundation                 0x18f36abc8 CFRunLoopRunSpecific
27 GraphicsServices               0x19974c5cc GSEventRunModal
28 UIKitCore                      0x19351d744 UIApplicationMain
29 OurAppName                       0x10498d668 main + 14 (main.m:14)
30 libdyld.dylib                  0x18f1e7384 start
```

**Comment by AliAbdelfattah** [comment]
This issue is a bit old, @mrarronz by any chance are you still getting this error on our latest version?
