### ISSUE TITLE
[Android] Updating to 10.0.0 crashing the app immediately after launch.

### ISSUE THREAD

**Issue by PavithraPurushothaman-T2S** [Instabug/Instabug-React-Native#553]
### Steps to Reproduce the Problem
Update the package instabug-reactnative to 10.0.0 
Run the app
App gets crash

### Expected Behavior
App should run

### Actual Behavior
App is crashing immediately after launch

### SDK Version
10.0.0

### React Native Versions
0.61.5

**Comment by Soliman13** [comment]
+1

I got the same issue, with react native 0.63.4

**Comment by AliAbdelfattah** [comment]
@PavithraPurushothaman-T2S could you share the crash logs? Also which OS and OS version?

**Comment by PavithraPurushothaman-T2S** [comment]
Android-> failed with this exception

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instabug-reactnative:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/dev/Documents/Projects/GitHub/customer_app_2.0/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by AliAbdelfattah** [comment]
@PavithraPurushothaman-T2S the error you posted is related to your JDK environment, this [SOF answer](https://stackoverflow.com/questions/64968851/could-not-find-tools-jar-please-check-that-library-internet-plug-ins-javaapple) should help.

**Comment by divyasri93** [comment]
Initially I was having instabug version 9.0.1 and it worked fine. The moment I upgraded it to 10.0.0, its keep on crashing in android 8.0.0 with the following error log 

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.moneyceo.yaac/com.instabug.library.ui.onboarding.OnboardingActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation

Here is my build.gradle 

        `buildToolsVersion` = "28.0.3"
        `minSdkVersion` = 21
        `compileSdkVersion` = 29
        `targetSdkVersion` = 29

**Comment by AliAbdelfattah** [comment]
@divyasri93 could you share your integration code please? Also, which version of RN do you have?

**Comment by divyasri93** [comment]
> @divyasri93 could you share your integration code please? Also, which version of RN do you have?

please note, 

react-native: 0.63.2

Integration code
   ```
 new RNInstabugReactnativePackage
    .Builder("****************token**************", MainApplication.this)
    .setInvocationEvent("shake","button")
    .setPrimaryColor("#1D82DC")
    .setFloatingEdge("left")
    .setFloatingButtonOffsetFromTop(250)
    .build();
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
```

**Comment by AliAbdelfattah** [comment]
@divyasri93 thank you, we're looking into it.

**Comment by tomwanzek** [comment]
This is a critical issue.

I can confirm that our App crashes after upgrade to SDK 10.0.0. (We upgraded in the same token as trying to address critical Google compliance issue the issue https://github.com/Instabug/Instabug-React-Native/issues/582 )

For me the app crashed on a physical iPhone 11 XS w/ iOS 1.4.2 deployed from our staging environment (Testflight). The crash is immediate during the splash screen. We had not issue with the prior SDK 9.8.1 version.

Additional info:

When running the app with the changes in the emulator of the same code base promoted to staging, and iPhone 11 Emulator w/ iOS 14.4 runs without crashing on the splash screen. However, when pointing to our Staging instabug instance an forcing a non-fatal error we know will get reported to Instabug, the error does not seem to appear in the Instabug crash log.

System Info for build:

```
System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 33.54 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.0 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1620264129455-0.19294985697386946/node
    Yarn: 1.22.5 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1620264129455-0.19294985697386946/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AliAbdelfattah** [comment]
@tomwanzek it seems this is a different issue than the one reported here. Could you please create a separate issue?

**Comment by tomwanzek** [comment]
@AliAbdelfattah there is also https://github.com/Instabug/Instabug-React-Native/issues/581 which seems the same. I already cross-referenced my above comment there, but can copy/paste it. 🙇

**Comment by AliAbdelfattah** [comment]
@divyasri93 we've pushed a potential fix in the latest release v10.4, please give it a try and let us know if it fixes your issue.

**Comment by divyasri93** [comment]
@AliAbdelfattah I've upgraded to 10.4.0 ... but still facing the same crash in Android 8.0.0 

Please check the full log text 

>```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.instabug.library.invocation.invocationdialog.InstabugDialogActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	 at android.app.ActivityThread.-wrap11(Unknown Source:0)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	 at android.os.Handler.dispatchMessage(Handler.java:105)
	 at android.os.Looper.loop(Looper.java:164)
	 at android.app.ActivityThread.main(ActivityThread.java:6541)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Caused by: 
java.lang.IllegalStateException: Only fullscreen activities can request orientation
	 at android.os.Parcel.readException(Parcel.java:1950)
	 at android.os.Parcel.readException(Parcel.java:1888)
	 at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
	 at android.app.Activity.setRequestedOrientation(Activity.java:5739)
	 at com.moneyceo.yaac.MainApplication$2.onActivityCreated(MainApplication.java:77)
	 at android.app.Application.dispatchActivityCreated(Application.java:197)
	 at android.app.Activity.onCreate(Activity.java:1015)
	 at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
	 at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:149)
	 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:313)
	 at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	 at com.instabug.library.core.ui.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:7)
	 at com.instabug.library.invocation.invocationdialog.InstabugDialogActivity.onCreate(InstabugDialogActivity.java:2)
	 at android.app.Activity.performCreate(Activity.java:6975)
	 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	 at android.app.ActivityThread.-wrap11(Unknown Source:0)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	 at android.os.Handler.dispatchMessage(Handler.java:105)
	 at android.os.Looper.loop(Looper.java:164)
	 at android.app.ActivityThread.main(ActivityThread.java:6541)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by divyasri93** [comment]
@AliAbdelfattah please let me know if any update on this fix, Thanks.

**Comment by AliAbdelfattah** [comment]
@divyasri93 sorry, we haven't been able to reproduce the issue on our end. Would it be possible to send us a sample app where you can reproduce it?
